### ISSUE TITLE
Is there nothing here?

### ISSUE THREAD

**Issue by dimaqq** [kpavlov/dynamodb-local-docker#1]
Repo seems empty :)

Pardon me if I dunno what the repo is for, though just in case here are some hints to run dynamo in docker:
* `dynalite` is a reimplementation of dynamodb in Javascript, although it has some limitations, it's better and much much lighter than dynamodb local from amazon:
  * image: https://hub.docker.com/r/dimaqq/dynalite/
  * source: https://github.com/dimaqq/dynalite-docker
  * underlying software: https://github.com/mhart/dynalite
* dynamodb local from amazon:
  * https://github.com/dwmkerr/docker-dynamodb
  * underlying software: somewhere on amazon

**Comment by kpavlov** [comment]
Just pushed something ;)
